server:
  port: 9101

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:270m
      embedding:
        model: nomic-embed-text:v1.5
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        initialize-schema: true
        database-name: "default"
        collection-name: "spring_ai2_poc_ollama"
        embedding-dimension: 768

logging:
  level:
    root: INFO
    io.will.springai2poc: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG