@baseUrl=http://localhost:9101

###
GET {{baseUrl}}/ping

###
POST {{baseUrl}}/chat
Content-Type: application/json

{
  "message": "This is a test message. Please simply let me know if you are working."
}

###
POST {{baseUrl}}/web-content/retrieve
Content-Type: application/json

{
  "question": "What is an agent?"
}

